language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION=^6.2.0
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=^8.5.0
  - TYPO3_VERSION="dev-master as 8.5"

matrix:
  exclude:
    - php: 7
      env: TYPO3_VERSION=^6.2.0
    - php: 5.4
      env: TYPO3_VERSION=^7.6.0
    - php: 5.4
      env: TYPO3_VERSION=^8.5.0
    - php: 5.5
      env: TYPO3_VERSION=^8.5.0
    - php: 5.6
      env: TYPO3_VERSION=^8.5.0
    - php: 5.4
      env: TYPO3_VERSION="dev-master as 8.5"
    - php: 5.5
      env: TYPO3_VERSION="dev-master as 8.5"
    - php: 5.6
      env: TYPO3_VERSION="dev-master as 8.5"

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  # First we install all required packages as dist versions.
  - composer require "typo3/cms=$TYPO3_VERSION" --prefer-dist
  # Now remove the TYPO3 core and all related symlinks.
  - rm -Rf .Build/vendor/typo3/cms
  - rm -f .Build/Web/typo3
  - rm -f .Build/Web/index.php
  # Finally we install the TYPO3 core as source version because we need some functional
  # test classes that are not included in the dist versions.
  - composer install --prefer-source
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - if [ -d $PWD/.Build/vendor/typo3/cms/components ]; then ln -s "$PWD/.Build/vendor/typo3/cms/components" .Build/Web/components; fi

script:
  - >
    echo;
    echo "Determining phpunit config path";
    if [ -d ".Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build" ]; then
      export PHPUNIT_CONFIG_PATH=".Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build";
    else
      export PHPUNIT_CONFIG_PATH=".Build/vendor/typo3/cms/typo3/sysext/core/Build";
    fi
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c $PHPUNIT_CONFIG_PATH/UnitTests.xml Tests/Unit/
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find . -wholename '*Tests/Functional/*Test.php' ! -path "./.Build/*" | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors -c $PHPUNIT_CONFIG_PATH/FunctionalTests.xml {}'
